apiVersion: v1
kind: Pod
metadata:
  name: liveness-app
  labels:
    app: liveness-app
spec:
  containers:
  - name: liveness-app-container
    image: your-app-image:latest
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
