apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      containers:
      - name: app-job-container
        image: your-app-image:latest
        args:
        - /bin/sh
        - -c
        - "echo Hello, Kubernetes! && date"
      restartPolicy: Never
  backoffLimit: 4
