apiVersion: v1
kind: Pod
metadata:
  name: readiness-app
  labels:
    app: readiness-app
spec:
  containers:
  - name: readiness-app-container
    image: your-app-image:latest
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
