apiVersion: v1
kind: Pod
metadata:
  name: app-multicontainer
  labels:
    app: multicontainer-app
spec:
  containers:
  - name: app-container-1
    image: your-app-image-1:latest
    ports:
    - containerPort: 8080
  - name: app-container-2
    image: your-app-image-2:latest
    ports:
    - containerPort: 8081
