apiVersion: v1
kind: Pod
metadata:
  name: app-with-volumes
  labels:
    app: volume-app
spec:
  containers:
  - name: volume-app-container
    image: your-app-image:latest
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    - name: data-volume
      mountPath: /var/data
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc
