apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
  labels:
    app: secret-env-app
spec:
  containers:
  - name: secret-env-app-container
    image: your-app-image:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
