apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-cronjob-container
            image: your-app-image:latest
            args:
            - /bin/sh
            - -c
            - "echo Hello, Kubernetes! && date"
          restartPolicy: OnFailure
